
package ar.com.educacionit.app.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VinotecaWS", targetNamespace = "http://service.app.educacionit.com.ar/", wsdlLocation = "file:/Users/rdurante/Desktop/carpeta%20sin%20t\u00edtulo/wsdl/servicio.wsdl")
public class VinotecaWS
    extends Service
{

    private final static URL VINOTECAWS_WSDL_LOCATION;
    private final static WebServiceException VINOTECAWS_EXCEPTION;
    private final static QName VINOTECAWS_QNAME = new QName("http://service.app.educacionit.com.ar/", "VinotecaWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/rdurante/Desktop/carpeta%20sin%20t\u00edtulo/wsdl/servicio.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VINOTECAWS_WSDL_LOCATION = url;
        VINOTECAWS_EXCEPTION = e;
    }

    public VinotecaWS() {
        super(__getWsdlLocation(), VINOTECAWS_QNAME);
    }

    public VinotecaWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), VINOTECAWS_QNAME, features);
    }

    public VinotecaWS(URL wsdlLocation) {
        super(wsdlLocation, VINOTECAWS_QNAME);
    }

    public VinotecaWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VINOTECAWS_QNAME, features);
    }

    public VinotecaWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VinotecaWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioVinotecaPortType
     */
    @WebEndpoint(name = "ServicioVinotecaPort")
    public ServicioVinotecaPortType getServicioVinotecaPort() {
        return super.getPort(new QName("http://service.app.educacionit.com.ar/", "ServicioVinotecaPort"), ServicioVinotecaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioVinotecaPortType
     */
    @WebEndpoint(name = "ServicioVinotecaPort")
    public ServicioVinotecaPortType getServicioVinotecaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.app.educacionit.com.ar/", "ServicioVinotecaPort"), ServicioVinotecaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VINOTECAWS_EXCEPTION!= null) {
            throw VINOTECAWS_EXCEPTION;
        }
        return VINOTECAWS_WSDL_LOCATION;
    }

}
