
package ar.com.educacionit.app.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioVinotecaPortType", targetNamespace = "http://service.app.educacionit.com.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioVinotecaPortType {


    /**
     * 
     * @param nombreDelVino
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerBodega")
    @WebResult(name = "nombreBodega", targetNamespace = "")
    @RequestWrapper(localName = "ObtenerBodega", targetNamespace = "http://service.app.educacionit.com.ar/", className = "ar.com.educacionit.app.service.ObtenerBodegaType")
    @ResponseWrapper(localName = "ObtenerBodegaResponse", targetNamespace = "http://service.app.educacionit.com.ar/", className = "ar.com.educacionit.app.service.ObtenerBodegaResponseType")
    public String obtenerBodega(
        @WebParam(name = "nombreDelVino", targetNamespace = "")
        String nombreDelVino);

}
